/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cooperativa.vista;

/**
 *
 * @author ftorrejon
 */
public class VentanaRegistrar extends javax.swing.JFrame {

  /**
   * Creates new form VentanaRegistrar
   */
  public VentanaRegistrar() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelSubtitulo = new javax.swing.JLabel();
    labelTitulo = new javax.swing.JLabel();
    panelArchivo = new javax.swing.JPanel();
    labelIdArchivo = new javax.swing.JLabel();
    labelFechaIngreso = new javax.swing.JLabel();
    labelResponsableDigitalizacion = new javax.swing.JLabel();
    labelCodigoSoporte = new javax.swing.JLabel();
    labelTipoSoporte = new javax.swing.JLabel();
    labelDescripcionExterior = new javax.swing.JLabel();
    labelNombreArchivo = new javax.swing.JLabel();
    labelTamanhoArchivo = new javax.swing.JLabel();
    labelDuracionArchivo = new javax.swing.JLabel();
    labelFormatoArchivo = new javax.swing.JLabel();
    labelFechaDigitalizacion = new javax.swing.JLabel();
    panelAgregarPrograma = new javax.swing.JPanel();
    labelIdPrograma = new javax.swing.JLabel();
    labelAlturaInicioPrograma = new javax.swing.JLabel();
    labelAlturaTerminoPrograma = new javax.swing.JLabel();
    labelNombrePrograma = new javax.swing.JLabel();
    labelConductor = new javax.swing.JLabel();
    labelAlturaTerminoPrograma3 = new javax.swing.JLabel();
    panelAgregarFragmento = new javax.swing.JPanel();
    labelIdAudio = new javax.swing.JLabel();
    panelTipos = new javax.swing.JLayeredPane();
    panelNoticia = new javax.swing.JPanel();
    labelTemaNoticia = new javax.swing.JLabel();
    panelInforme = new javax.swing.JPanel();
    labelTemaInforme = new javax.swing.JLabel();
    labelPeriodistaInforme = new javax.swing.JLabel();
    labelLugarInforme = new javax.swing.JLabel();
    labelPersonajeInforme = new javax.swing.JLabel();
    panelSeccion = new javax.swing.JPanel();
    labelPanelistasSeccion = new javax.swing.JLabel();
    labelNombreSeccion = new javax.swing.JLabel();
    labelTemaSeccion = new javax.swing.JLabel();
    labelInvitadosSeccion = new javax.swing.JLabel();
    panelPanel = new javax.swing.JPanel();
    labelPanelistas = new javax.swing.JLabel();
    labelTemaEntrevista1 = new javax.swing.JLabel();
    panelDeporte = new javax.swing.JPanel();
    labelLocutorComercial = new javax.swing.JLabel();
    labelRelator = new javax.swing.JLabel();
    labelEncargadoRRSS = new javax.swing.JLabel();
    labelCompetencia = new javax.swing.JLabel();
    labelLugar = new javax.swing.JLabel();
    labelDisciplina = new javax.swing.JLabel();
    panelDisciplina = new javax.swing.JLayeredPane();
    panelFutbol = new javax.swing.JPanel();
    labelEquipoLocalFutbol = new javax.swing.JLabel();
    labelEquipoVisitaFutbol = new javax.swing.JLabel();
    labelMarcadorFinalFutbol = new javax.swing.JLabel();
    labelGoles = new javax.swing.JLabel();
    panelTenis = new javax.swing.JPanel();
    labelJugadores = new javax.swing.JLabel();
    labelMarcadorFinalTenis = new javax.swing.JLabel();
    panelBasquetball = new javax.swing.JPanel();
    labelEquipoLocalBasquetball = new javax.swing.JLabel();
    labelEquipoVisitaBasquetball = new javax.swing.JLabel();
    labelMarcadorFinalBasquetball = new javax.swing.JLabel();
    panelEntrevista = new javax.swing.JPanel();
    labelEntrevistados = new javax.swing.JLabel();
    labelPeriodistaEntrevista = new javax.swing.JLabel();
    labelTemaEntrevista = new javax.swing.JLabel();
    labelTipoAudio = new javax.swing.JLabel();
    labelAlturaInicioFragmento = new javax.swing.JLabel();
    labelAlturaTerminoFragmento = new javax.swing.JLabel();
    labelDescripcion = new javax.swing.JLabel();
    labelPalabrasClave = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    labelSubtitulo.setText("Archivo Radio Cooperativa");

    labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    labelTitulo.setText("REGISTRO DE ARCHIVOS");

    panelArchivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Archivo"));

    labelIdArchivo.setText("Id Archivo");

    labelFechaIngreso.setText("Fecha Ingreso");

    labelResponsableDigitalizacion.setText("Responsable Digitalización");

    labelCodigoSoporte.setText("Código de Soporte");

    labelTipoSoporte.setText("Tipo Soporte");

    labelDescripcionExterior.setText("Descripcion Exterior");

    labelNombreArchivo.setText("Nombre de Archivo");

    labelTamanhoArchivo.setText("Tamaño");

    labelDuracionArchivo.setText("Duración");

    labelFormatoArchivo.setText("Formato");

    labelFechaDigitalizacion.setText("Fecha de Digitalización");

    javax.swing.GroupLayout panelArchivoLayout = new javax.swing.GroupLayout(panelArchivo);
    panelArchivo.setLayout(panelArchivoLayout);
    panelArchivoLayout.setHorizontalGroup(
      panelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelArchivoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelArchivoLayout.createSequentialGroup()
            .addGroup(panelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(labelFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(labelIdArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(labelResponsableDigitalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelCodigoSoporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelTipoSoporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelDescripcionExterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelNombreArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelTamanhoArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelDuracionArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelFormatoArchivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(labelFechaDigitalizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(112, 112, 112))
    );
    panelArchivoLayout.setVerticalGroup(
      panelArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelArchivoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelIdArchivo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelFechaIngreso)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelResponsableDigitalizacion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelCodigoSoporte)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTipoSoporte)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelDescripcionExterior)
        .addGap(18, 18, 18)
        .addComponent(labelNombreArchivo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTamanhoArchivo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelDuracionArchivo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelFormatoArchivo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelFechaDigitalizacion)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelAgregarPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Programa"));

    labelIdPrograma.setText("Id Programa");

    labelAlturaInicioPrograma.setText("Altura Inicio");

    labelAlturaTerminoPrograma.setText("Altura Término");

    labelNombrePrograma.setText("Nombre del Programa");

    labelConductor.setText("Conductor");

    labelAlturaTerminoPrograma3.setText("Fecha Emision");

    javax.swing.GroupLayout panelAgregarProgramaLayout = new javax.swing.GroupLayout(panelAgregarPrograma);
    panelAgregarPrograma.setLayout(panelAgregarProgramaLayout);
    panelAgregarProgramaLayout.setHorizontalGroup(
      panelAgregarProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAgregarProgramaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAgregarProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(panelAgregarProgramaLayout.createSequentialGroup()
            .addComponent(labelIdPrograma)
            .addGap(149, 149, 149))
          .addGroup(panelAgregarProgramaLayout.createSequentialGroup()
            .addGroup(panelAgregarProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelAlturaTerminoPrograma)
              .addComponent(labelNombrePrograma)
              .addComponent(labelConductor)
              .addComponent(labelAlturaInicioPrograma)
              .addComponent(labelAlturaTerminoPrograma3))
            .addGap(0, 119, Short.MAX_VALUE))))
    );
    panelAgregarProgramaLayout.setVerticalGroup(
      panelAgregarProgramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAgregarProgramaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(labelIdPrograma)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelAlturaInicioPrograma)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelAlturaTerminoPrograma)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelNombrePrograma)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelAlturaTerminoPrograma3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelConductor)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelAgregarFragmento.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Fragmento"));

    labelIdAudio.setText("Id Audio");

    panelTipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    labelTemaNoticia.setText("Tema de la Noticia");

    javax.swing.GroupLayout panelNoticiaLayout = new javax.swing.GroupLayout(panelNoticia);
    panelNoticia.setLayout(panelNoticiaLayout);
    panelNoticiaLayout.setHorizontalGroup(
      panelNoticiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(labelTemaNoticia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    panelNoticiaLayout.setVerticalGroup(
      panelNoticiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(labelTemaNoticia)
    );

    panelTipos.setLayer(panelNoticia, 1);
    panelTipos.add(panelNoticia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    labelTemaInforme.setText("Tema del Informe");

    labelPeriodistaInforme.setText("Periodista");

    labelLugarInforme.setText("Lugar desde donde se informa");

    labelPersonajeInforme.setText("Cuñas en el Informe");

    javax.swing.GroupLayout panelInformeLayout = new javax.swing.GroupLayout(panelInforme);
    panelInforme.setLayout(panelInformeLayout);
    panelInformeLayout.setHorizontalGroup(
      panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(labelTemaInforme)
      .addComponent(labelPeriodistaInforme)
      .addComponent(labelLugarInforme)
      .addComponent(labelPersonajeInforme)
    );
    panelInformeLayout.setVerticalGroup(
      panelInformeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelInformeLayout.createSequentialGroup()
        .addComponent(labelPeriodistaInforme)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTemaInforme)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelLugarInforme)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelPersonajeInforme)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelTipos.setLayer(panelInforme, 2);
    panelTipos.add(panelInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    labelPanelistasSeccion.setText("Panelistas");

    labelNombreSeccion.setText("Nombre de la Sección");

    labelTemaSeccion.setText("Tema");

    labelInvitadosSeccion.setText("Invitados");

    javax.swing.GroupLayout panelSeccionLayout = new javax.swing.GroupLayout(panelSeccion);
    panelSeccion.setLayout(panelSeccionLayout);
    panelSeccionLayout.setHorizontalGroup(
      panelSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelSeccionLayout.createSequentialGroup()
        .addGroup(panelSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelPanelistasSeccion)
          .addComponent(labelNombreSeccion)
          .addComponent(labelTemaSeccion)
          .addComponent(labelInvitadosSeccion))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    panelSeccionLayout.setVerticalGroup(
      panelSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelSeccionLayout.createSequentialGroup()
        .addComponent(labelNombreSeccion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelPanelistasSeccion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTemaSeccion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelInvitadosSeccion))
    );

    panelTipos.setLayer(panelSeccion, 3);
    panelTipos.add(panelSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    labelPanelistas.setText("Entrevistados");

    labelTemaEntrevista1.setText("Tema");

    javax.swing.GroupLayout panelPanelLayout = new javax.swing.GroupLayout(panelPanel);
    panelPanel.setLayout(panelPanelLayout);
    panelPanelLayout.setHorizontalGroup(
      panelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPanelLayout.createSequentialGroup()
        .addGroup(panelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelPanelistas)
          .addComponent(labelTemaEntrevista1))
        .addGap(0, 94, Short.MAX_VALUE))
    );
    panelPanelLayout.setVerticalGroup(
      panelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelPanelLayout.createSequentialGroup()
        .addComponent(labelPanelistas)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTemaEntrevista1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelTipos.setLayer(panelPanel, 6);
    panelTipos.add(panelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    labelLocutorComercial.setText("Locutor Comercial");

    labelRelator.setText("Relator");

    labelEncargadoRRSS.setText("Encargado Redes Sociales");

    labelCompetencia.setText("Competencia");

    labelLugar.setText("Lugar");

    labelDisciplina.setText("Disciplina");

    panelDisciplina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    panelFutbol.setAlignmentX(0.0F);
    panelFutbol.setAlignmentY(0.0F);

    labelEquipoLocalFutbol.setText("Equipo Local");

    labelEquipoVisitaFutbol.setText("Equipo Visita");

    labelMarcadorFinalFutbol.setText("Marcador Final");

    labelGoles.setText("Goles");

    javax.swing.GroupLayout panelFutbolLayout = new javax.swing.GroupLayout(panelFutbol);
    panelFutbol.setLayout(panelFutbolLayout);
    panelFutbolLayout.setHorizontalGroup(
      panelFutbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelFutbolLayout.createSequentialGroup()
        .addGroup(panelFutbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelEquipoLocalFutbol)
          .addComponent(labelEquipoVisitaFutbol)
          .addComponent(labelMarcadorFinalFutbol)
          .addComponent(labelGoles))
        .addGap(0, 8, Short.MAX_VALUE))
    );
    panelFutbolLayout.setVerticalGroup(
      panelFutbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelFutbolLayout.createSequentialGroup()
        .addComponent(labelEquipoLocalFutbol)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelEquipoVisitaFutbol)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelMarcadorFinalFutbol)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelGoles))
    );

    panelDisciplina.setLayer(panelFutbol, 6);
    panelDisciplina.add(panelFutbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    panelTenis.setAlignmentX(0.0F);
    panelTenis.setAlignmentY(0.0F);

    labelJugadores.setText("Equipo Local");

    labelMarcadorFinalTenis.setText("Marcador Final");

    javax.swing.GroupLayout panelTenisLayout = new javax.swing.GroupLayout(panelTenis);
    panelTenis.setLayout(panelTenisLayout);
    panelTenisLayout.setHorizontalGroup(
      panelTenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelTenisLayout.createSequentialGroup()
        .addGroup(panelTenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelJugadores)
          .addComponent(labelMarcadorFinalTenis))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelTenisLayout.setVerticalGroup(
      panelTenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelTenisLayout.createSequentialGroup()
        .addComponent(labelJugadores)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelMarcadorFinalTenis)
        .addContainerGap())
    );

    panelDisciplina.setLayer(panelTenis, 8);
    panelDisciplina.add(panelTenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    panelBasquetball.setAlignmentX(0.0F);
    panelBasquetball.setAlignmentY(0.0F);

    labelEquipoLocalBasquetball.setText("Equipo Local");

    labelEquipoVisitaBasquetball.setText("Equipo Visita");

    labelMarcadorFinalBasquetball.setText("Marcador Final");

    javax.swing.GroupLayout panelBasquetballLayout = new javax.swing.GroupLayout(panelBasquetball);
    panelBasquetball.setLayout(panelBasquetballLayout);
    panelBasquetballLayout.setHorizontalGroup(
      panelBasquetballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelBasquetballLayout.createSequentialGroup()
        .addGroup(panelBasquetballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelEquipoLocalBasquetball)
          .addComponent(labelEquipoVisitaBasquetball)
          .addComponent(labelMarcadorFinalBasquetball))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    panelBasquetballLayout.setVerticalGroup(
      panelBasquetballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelBasquetballLayout.createSequentialGroup()
        .addComponent(labelEquipoLocalBasquetball)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelEquipoVisitaBasquetball)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelMarcadorFinalBasquetball)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelDisciplina.setLayer(panelBasquetball, 7);
    panelDisciplina.add(panelBasquetball, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    javax.swing.GroupLayout panelDeporteLayout = new javax.swing.GroupLayout(panelDeporte);
    panelDeporte.setLayout(panelDeporteLayout);
    panelDeporteLayout.setHorizontalGroup(
      panelDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDeporteLayout.createSequentialGroup()
        .addGroup(panelDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelLocutorComercial)
          .addComponent(labelRelator)
          .addComponent(labelEncargadoRRSS)
          .addComponent(labelCompetencia)
          .addComponent(labelLugar)
          .addComponent(labelDisciplina))
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeporteLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(panelDisciplina)
        .addContainerGap())
    );
    panelDeporteLayout.setVerticalGroup(
      panelDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelDeporteLayout.createSequentialGroup()
        .addComponent(labelRelator)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelLocutorComercial)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelEncargadoRRSS)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelCompetencia)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelLugar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelDisciplina)
        .addGap(18, 18, 18)
        .addComponent(panelDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    panelTipos.setLayer(panelDeporte, 5);
    panelTipos.add(panelDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    labelEntrevistados.setText("Entrevistados");

    labelPeriodistaEntrevista.setText("Periodista");

    labelTemaEntrevista.setText("Tema");

    javax.swing.GroupLayout panelEntrevistaLayout = new javax.swing.GroupLayout(panelEntrevista);
    panelEntrevista.setLayout(panelEntrevistaLayout);
    panelEntrevistaLayout.setHorizontalGroup(
      panelEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEntrevistaLayout.createSequentialGroup()
        .addGroup(panelEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelEntrevistados)
          .addComponent(labelPeriodistaEntrevista)
          .addComponent(labelTemaEntrevista))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    panelEntrevistaLayout.setVerticalGroup(
      panelEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelEntrevistaLayout.createSequentialGroup()
        .addComponent(labelPeriodistaEntrevista)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelEntrevistados)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTemaEntrevista))
    );

    panelTipos.setLayer(panelEntrevista, 4);
    panelTipos.add(panelEntrevista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    labelTipoAudio.setText("Tipo de Audio");

    labelAlturaInicioFragmento.setText("Altura de Inicio");

    labelAlturaTerminoFragmento.setText("Altura de Término");

    labelDescripcion.setText("Descripcion");

    labelPalabrasClave.setText("Palabras Clave");

    javax.swing.GroupLayout panelAgregarFragmentoLayout = new javax.swing.GroupLayout(panelAgregarFragmento);
    panelAgregarFragmento.setLayout(panelAgregarFragmentoLayout);
    panelAgregarFragmentoLayout.setHorizontalGroup(
      panelAgregarFragmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAgregarFragmentoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelAgregarFragmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelTipos)
          .addGroup(panelAgregarFragmentoLayout.createSequentialGroup()
            .addGroup(panelAgregarFragmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelIdAudio)
              .addComponent(labelTipoAudio)
              .addComponent(labelAlturaInicioFragmento)
              .addComponent(labelAlturaTerminoFragmento)
              .addComponent(labelDescripcion)
              .addComponent(labelPalabrasClave))
            .addGap(0, 98, Short.MAX_VALUE)))
        .addContainerGap())
    );
    panelAgregarFragmentoLayout.setVerticalGroup(
      panelAgregarFragmentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelAgregarFragmentoLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelIdAudio)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelAlturaInicioFragmento)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelAlturaTerminoFragmento)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelTipoAudio)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelDescripcion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelPalabrasClave))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelTitulo)
          .addComponent(labelSubtitulo)
          .addGroup(layout.createSequentialGroup()
            .addComponent(panelArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(panelAgregarPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelAgregarFragmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(40, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(labelTitulo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelSubtitulo)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(panelAgregarPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelAgregarFragmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        new VentanaRegistrar().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel labelAlturaInicioFragmento;
  private javax.swing.JLabel labelAlturaInicioPrograma;
  private javax.swing.JLabel labelAlturaTerminoFragmento;
  private javax.swing.JLabel labelAlturaTerminoPrograma;
  private javax.swing.JLabel labelAlturaTerminoPrograma3;
  private javax.swing.JLabel labelCodigoSoporte;
  private javax.swing.JLabel labelCompetencia;
  private javax.swing.JLabel labelConductor;
  private javax.swing.JLabel labelDescripcion;
  private javax.swing.JLabel labelDescripcionExterior;
  private javax.swing.JLabel labelDisciplina;
  private javax.swing.JLabel labelDuracionArchivo;
  private javax.swing.JLabel labelEncargadoRRSS;
  private javax.swing.JLabel labelEntrevistados;
  private javax.swing.JLabel labelEquipoLocalBasquetball;
  private javax.swing.JLabel labelEquipoLocalFutbol;
  private javax.swing.JLabel labelEquipoVisitaBasquetball;
  private javax.swing.JLabel labelEquipoVisitaFutbol;
  private javax.swing.JLabel labelFechaDigitalizacion;
  private javax.swing.JLabel labelFechaIngreso;
  private javax.swing.JLabel labelFormatoArchivo;
  private javax.swing.JLabel labelGoles;
  private javax.swing.JLabel labelIdArchivo;
  private javax.swing.JLabel labelIdAudio;
  private javax.swing.JLabel labelIdPrograma;
  private javax.swing.JLabel labelInvitadosSeccion;
  private javax.swing.JLabel labelJugadores;
  private javax.swing.JLabel labelLocutorComercial;
  private javax.swing.JLabel labelLugar;
  private javax.swing.JLabel labelLugarInforme;
  private javax.swing.JLabel labelMarcadorFinalBasquetball;
  private javax.swing.JLabel labelMarcadorFinalFutbol;
  private javax.swing.JLabel labelMarcadorFinalTenis;
  private javax.swing.JLabel labelNombreArchivo;
  private javax.swing.JLabel labelNombrePrograma;
  private javax.swing.JLabel labelNombreSeccion;
  private javax.swing.JLabel labelPalabrasClave;
  private javax.swing.JLabel labelPanelistas;
  private javax.swing.JLabel labelPanelistasSeccion;
  private javax.swing.JLabel labelPeriodistaEntrevista;
  private javax.swing.JLabel labelPeriodistaInforme;
  private javax.swing.JLabel labelPersonajeInforme;
  private javax.swing.JLabel labelRelator;
  private javax.swing.JLabel labelResponsableDigitalizacion;
  private javax.swing.JLabel labelSubtitulo;
  private javax.swing.JLabel labelTamanhoArchivo;
  private javax.swing.JLabel labelTemaEntrevista;
  private javax.swing.JLabel labelTemaEntrevista1;
  private javax.swing.JLabel labelTemaInforme;
  private javax.swing.JLabel labelTemaNoticia;
  private javax.swing.JLabel labelTemaSeccion;
  private javax.swing.JLabel labelTipoAudio;
  private javax.swing.JLabel labelTipoSoporte;
  private javax.swing.JLabel labelTitulo;
  private javax.swing.JPanel panelAgregarFragmento;
  private javax.swing.JPanel panelAgregarPrograma;
  private javax.swing.JPanel panelArchivo;
  private javax.swing.JPanel panelBasquetball;
  private javax.swing.JPanel panelDeporte;
  private javax.swing.JLayeredPane panelDisciplina;
  private javax.swing.JPanel panelEntrevista;
  private javax.swing.JPanel panelFutbol;
  private javax.swing.JPanel panelInforme;
  private javax.swing.JPanel panelNoticia;
  private javax.swing.JPanel panelPanel;
  private javax.swing.JPanel panelSeccion;
  private javax.swing.JPanel panelTenis;
  private javax.swing.JLayeredPane panelTipos;
  // End of variables declaration//GEN-END:variables
}
