/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cooperativa.vista;
import com.cooperativa.model.*;
import com.cooperativa.dao.ArchivoDaoImpl;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ftorrejon
 */
public class VentanaComentario extends javax.swing.JFrame {
  
  private String operador;
  private String idArchivo;
  private ArchivoDaoImpl archivoDao = new ArchivoDaoImpl();
      
      ;
  private int idCambio;
  private List<Cambio> cambios;
  
  /**
   * Creates new form VentanaComentario
   * @param operador
   * @param idArchivo
   */
  public VentanaComentario(String operador,String idArchivo) {
    this.operador = operador;
    this.idArchivo = idArchivo;
    
    initComponents();
    
    this.labelOperador.setText(this.operador);
    this.valueIdArchivo.setText(this.idArchivo);
    
    completarTabla();
  }
  
  //metodos personalizados
  
  private void completarTabla() {
    DefaultTableModel modelo = (DefaultTableModel)tablaHistorial.getModel();
    
    try {
      int counter = 0;
      cambios = archivoDao.listarCambios(this.idArchivo);
      for(Cambio c: cambios){
        modelo.addRow(new String[4]);
        modelo.setValueAt(c.getIdCambio(), counter, 0);
        modelo.setValueAt(c.getFechaCambio(), counter, 1);
        modelo.setValueAt(c.getResponsableCambio(), counter, 2);
        modelo.setValueAt(c.getDescripcion(), counter, 3);
        counter++;
      }
    } catch(Exception e){
      System.out.println("...CUEK---");
      e.printStackTrace();
    }
    tablaHistorial.setModel(modelo);
    this.idCambio = cambios.size();
  }
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelTitulo = new javax.swing.JLabel();
    labelOperador = new javax.swing.JLabel();
    labelIdArchivo = new javax.swing.JLabel();
    valueIdArchivo = new javax.swing.JLabel();
    scrollDescripcion = new javax.swing.JScrollPane();
    textDescripcion = new javax.swing.JTextArea();
    botonGuardar = new javax.swing.JButton();
    scrollHistorial = new javax.swing.JScrollPane();
    tablaHistorial = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    labelTitulo.setText("CONTROL DE CAMBIOS");

    labelOperador.setText("Operador");

    labelIdArchivo.setText("Id Archivo");

    scrollDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción último cambio"));

    textDescripcion.setColumns(20);
    textDescripcion.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
    textDescripcion.setRows(5);
    textDescripcion.setTabSize(4);
    textDescripcion.setText("Correcciones menores");
    scrollDescripcion.setViewportView(textDescripcion);

    botonGuardar.setText("Guardar y Salir");
    botonGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonGuardarActionPerformed(evt);
      }
    });

    scrollHistorial.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial de Cambios"));

    tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "#", "Fecha", "Operador", "Descripcion"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tablaHistorial.setRowSelectionAllowed(false);
    tablaHistorial.getTableHeader().setReorderingAllowed(false);
    scrollHistorial.setViewportView(tablaHistorial);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(scrollDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(labelIdArchivo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(valueIdArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addComponent(labelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelOperador)))
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(botonGuardar)
            .addGap(19, 19, 19))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(scrollHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelTitulo)
          .addComponent(labelOperador))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelIdArchivo)
          .addComponent(valueIdArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(scrollDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(botonGuardar)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(scrollHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
    Cambio cambio = new Cambio();
    
    try {
      cambio.setIdCambio(this.idCambio);
      cambio.setResponsableCambio(this.operador);
      cambio.setDescripcion(textDescripcion.getText());
      
      if(archivoDao.agregarCambio(idArchivo, cambio)){
        System.out.println("-- Descripción de cambio en " + idArchivo + " agregada --");
        new VentanaPrincipal(this.operador).setVisible(true);
        this.dispose();
        
      } else {
        System.out.println("Cambio no agregado");
      }
      
    } catch(Exception e){
      
    }
  }//GEN-LAST:event_botonGuardarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VentanaComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VentanaComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VentanaComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VentanaComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VentanaComentario("operador","0000").setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonGuardar;
  private javax.swing.JLabel labelIdArchivo;
  private javax.swing.JLabel labelOperador;
  private javax.swing.JLabel labelTitulo;
  private javax.swing.JScrollPane scrollDescripcion;
  private javax.swing.JScrollPane scrollHistorial;
  private javax.swing.JTable tablaHistorial;
  private javax.swing.JTextArea textDescripcion;
  private javax.swing.JLabel valueIdArchivo;
  // End of variables declaration//GEN-END:variables

}
