/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cooperativa.vista;

/**
 *
 * @author ftorrejon
 */
public class VentanaPrincipal extends javax.swing.JFrame {

  /**
   * Creates new form VentanaPrincipal
   */
  public VentanaPrincipal() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    botonARegistrar = new javax.swing.JButton();
    botonAModificar = new javax.swing.JButton();
    botonABusqueda = new javax.swing.JButton();
    enlaceSalir = new javax.swing.JLabel();
    labelTitulo = new javax.swing.JLabel();
    labelSubtitulo = new javax.swing.JLabel();
    labelRegistrar = new javax.swing.JLabel();
    labelRegistrar1 = new javax.swing.JLabel();
    labelRegistrar2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    botonARegistrar.setText("Registrar");
    botonARegistrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonARegistrarActionPerformed(evt);
      }
    });

    botonAModificar.setText("Modificar");
    botonAModificar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonAModificarActionPerformed(evt);
      }
    });

    botonABusqueda.setText("Buscar");
    botonABusqueda.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonABusquedaActionPerformed(evt);
      }
    });

    enlaceSalir.setText("Salir");
    enlaceSalir.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        enlaceSalirMouseClicked(evt);
      }
    });

    labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    labelTitulo.setText("BASE DE DATOS");

    labelSubtitulo.setText("Archivo Radio Cooperativa");

    labelRegistrar.setLabelFor(botonARegistrar);
    labelRegistrar.setText("<html>Acá podrás ingresar un nuevo archivo a la colección</html>");
    labelRegistrar.setInheritsPopupMenu(false);

    labelRegistrar1.setLabelFor(botonARegistrar);
    labelRegistrar1.setText("<html>Acá podrás modificar o eliminar un archivo de la colección</html>");
    labelRegistrar1.setInheritsPopupMenu(false);

    labelRegistrar2.setLabelFor(botonARegistrar);
    labelRegistrar2.setText("<html>Si quieres buscar en nuestra colección, éste es el lugar</html>");
    labelRegistrar2.setInheritsPopupMenu(false);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(enlaceSalir)
        .addGap(19, 19, 19))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelTitulo)
              .addComponent(labelSubtitulo)))
          .addGroup(layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
              .addComponent(botonARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(botonAModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(botonABusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(labelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(labelRegistrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(labelRegistrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(32, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(enlaceSalir)
          .addComponent(labelTitulo))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelSubtitulo)
        .addGap(41, 41, 41)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(botonARegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelRegistrar))
        .addGap(40, 40, 40)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(botonAModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelRegistrar1))
        .addGap(38, 38, 38)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(botonABusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(labelRegistrar2))
        .addGap(34, 34, 34))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonARegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonARegistrarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonARegistrarActionPerformed

  private void botonAModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAModificarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonAModificarActionPerformed

  private void botonABusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonABusquedaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonABusquedaActionPerformed

  private void enlaceSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enlaceSalirMouseClicked
    
  }//GEN-LAST:event_enlaceSalirMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VentanaPrincipal().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonABusqueda;
  private javax.swing.JButton botonAModificar;
  private javax.swing.JButton botonARegistrar;
  private javax.swing.JLabel enlaceSalir;
  private javax.swing.JLabel labelRegistrar;
  private javax.swing.JLabel labelRegistrar1;
  private javax.swing.JLabel labelRegistrar2;
  private javax.swing.JLabel labelSubtitulo;
  private javax.swing.JLabel labelTitulo;
  // End of variables declaration//GEN-END:variables
}
